=== AndrewMitchell25/Beaver/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Note",
    "type": "object",
    "properties": {
        "id": {
        "type": "integer"
        },
        "title": {
        "type": "string"
        },
        "content": {
        "type": "string"
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": ["id", "title", "content", "tags"]
}

=== AndrewMitchell25/Beaver/db.json
[
    {
        "title": "Books to Read",
        "content": "The Alchemist Educated by Tara asdasdasd",
        "tags": [
            "books",
            "dadadad"
        ],
        "id": 1
    },
    {
        "title": "Books to Read",
        "content": "The Alchemist Educated by Tara",
        "tags": [
            "books",
            "dadadad"
        ],
        "id": 2
    }
]
